export default function Privacy() {
  return (
    <div className="privacy">
      <h2>Privacy</h2>
      <div className="main_p">
        <h3>Privacy Policy</h3>
        <p>
          (“we,” “our,” or “us”) is committed to protecting your privacy. This
          Privacy Policy explains how your personal information is collected,
          used, and disclosed by us. This Privacy Policy applies to our website,
          and its associated subdomains (collectively, our “Service”) alongside
          our application. By accessing or using our Service, you signify that
          you have read, understood, and agree to our collection, storage, use,
          and disclosure of your personal information as described in this
          Privacy Policy and our Terms of Service.
        </p>

        <h3>Definitions and key terms</h3>
        <p>
          To help explain things as clearly as possible in this Privacy Policy,
          every time any of these terms are referenced, are strictly defined as:
        </p>
        <ul>
          <li>
            Cookie: small amount of data generated by a website and saved by
            your web browser. It is used to identify your browser, provide
            analytics, remember information about you such as your language
            preference or login information. ow
          </li>
          <li>
            Company: when this policy mentions “Company,” “we,” “us,” or “our,”
            it refers to our website, that is responsible for your information
            under this Privacy Policy.
          </li>
          <li>
            Country: where our website or the owners/founders of our website are
            based, in this case is Afghanistan
          </li>
          <li>
            Customer: refers to the company, organization or person that signs
            up to use the our website Service to manage the relationships with
            your consumers or service users.
          </li>
          <li>
            Device: any internet connected device such as a phone, tablet,
            computer or any other device that can be used to visit our website
            and use the services.
          </li>
          <li>
            IP address: Every device connected to the Internet is assigned a
            number known as an Internet protocol (IP) address. These numbers are
            usually assigned in geographic blocks. An IP address can often be
            used to identify the location from which a device is connecting to
            the Internet.
          </li>
          <li>
            Personnel: refers to those individuals who are employed by our
            organization or are under contract to perform a service on behalf of
            one of the parties.
          </li>
          <li>
            Personal Data: any information that directly, indirectly, or in
            connection with other information — including a personal
            identification number — allows for the identification or
            identifiability of a natural person.
          </li>
          <li>
            Service: refers to the service provided by our website as described
            in the relative terms (if available) and on this platform.
          </li>
          <li>
            Third-party service: refers to advertisers, contest sponsors,
            promotional and marketing partners, and others who provide our
            content or whose products or services we think may interest you.
          </li>
        </ul>
      </div>
    </div>
  );
}
